namespace: "argocd"
prefix: "name"
replicas: 2
spec:
  destination:
    server: "https://kubernetes.default.svc"
  project: "5b02f9dc"
  source:
    repoURL: "https://github.com/mteodor/argocd-example-apps"
    targetRevision: "HEAD"
revision: "syncstep-multisource"
